core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('home.urls')),
    path('', include('library.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.Home, name='home'),
]

library/urls.py
from django.urls import path

from . import views

app_name = 'library'

urlpatterns = [
    path('view_all_book/', views.all_books, name='all_books'),
    path('add/book/',views.add_book,name='add_book'),
    path('add/category/',views.add_category,name='add_category'),
    path('book_added/', views.book_added, name='book_added'),
    path('item/<slug:slug>/', views.book_detail, name='book_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('add/copy/', views.add_copy_form, name='add_copy'),
    path('owned/copy/', views.owned_copy, name='owned_books'),
    path('borrowed/copy/', views.borrowed_copy, name='borrowed_books'),
    path('borrow/<slug:slug>/', views.borrow_copy, name='borrow_copy'),
    path('searchbooks/', views.search_books, name='search_books'),

]

base/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages
from datetime import date, time, datetime
from django.contrib.auth.decorators import login_required


@login_required(login_url='/')
def Home(request):
    return render(request, 'pages/home.html')

templates/pages/add_book.html
{% extends 'pages/base.html' %}
{% load static %}
{% block basetemplate %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center mb-4">Add Book</h2>
      <form method="post" enctype="multipart/form-data" action="{% url 'library:add_book'%}">
        {% csrf_token %}
        <div class="form-group">
          {{ form.category.label_tag }}
          {{ form.category }}
        </div>
        <div class="form-group">
          {{ form.title.label_tag }}
          {{ form.title }}
        </div>
        <div class="form-group">
          {{ form.author.label_tag }}
          {{ form.author }}
        </div>
        <div class="form-group">
          {{ form.description.label_tag }}
          {{ form.description }}
        </div>
        <div class="form-group">
          {{ form.image.label_tag }}
          {{ form.image }}
        </div>
        <div class="form-group">
          {{ form.publisher.label_tag }}
          {{ form.publisher }}
        </div>
        <div class="form-group">
            {{ form.slug.label_tag }}
            {{ form.slug }}
          </div>
        <div class="form-group">
          {{ form.edition.label_tag }}
          {{ form.edition }}
        </div>
        <button type="submit" class="btn btn-primary">Add Book</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/pages/add_category.html
{% extends 'pages/base.html' %}
{% load static %}
{% block basetemplate %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center mb-4">Add Category</h2>
      <form method="post" enctype="multipart/form-data" action="{% url 'library:add_category'%}">
        {% csrf_token %}
        <div class="form-group">
          {{ form.name.label_tag }}
          {{ form.name }}
        </div>
        <div class="form-group">
          {{ form.slug.label_tag }}
          {{ form.slug }}
        </div>
        <button type="submit" class="btn btn-primary">Add Category</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/pages/add_copy.html
{% extends 'pages/base.html' %}
{% load static %}

{% block basetemplate %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center mb-4">Add Copy</h2>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          {{ form.book.label_tag }}
          {{ form.book }}
        </div>
        <div class="form-group">
          {{ form.copy.label_tag }}
          {{ form.copy }}
        </div>
        <button type="submit" class="btn btn-primary">Add Copy</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/pages/book_added.html
{% extends 'pages/base.html' %}
{% load static %}
{% block basetemplate %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center mb-4">Added Successfully</h2>
      <p class="text-center font-weight-bold">Thank you for adding</p>
    </div>
  </div>
</div>

{% endblock %}

templates/pages/borrowed_copy.html
{% extends 'pages/base.html' %}
{% load static %}
{% block basetemplate %}

<main>
    <div class="event-schedule-area-two bg-color pad100">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-20">
                <div class="section-title text-center">
                    <div class="title-text">
                        <h2>Borrowed Copy</h2>
                        
                    </div>
                </div>
            </div>
            <!-- /.col end-->
        </div>
        <!-- row end-->
        <div class="row">
            <div class="col-xl-20">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade active show" id="home" role="tabpanel">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
<!--                                        <th class="text-center" scope="col">Date</th>-->  
                                        <th scope="col">Sl</th>
                                        <th scope="col">Title</th>
                                        <th scope="col">Copy No</th>
                                        <th scope="col">Borrow date</th>
                                        <th scope="col">Copy Owner</th>
                                    </tr>
                                </thead>
                                <tbody>
                                 {% for borrow in borrowed_copies %}
                                    <tr class="inner-box">
                                        <td>
                                           </h2>{{ forloop.counter }}</h2>
                                        </td>
                                        <td>
                                            <div class="event-wrap">
                                                <h5 style="color: green">{{borrow.copy.book.title}}</a></h5>
                                            </div>
                                        </td>
                                        <td>
                                            
                                                <h5>{{ borrow.copy.copy}}</h5>
                                            
                                        </td>
                                        
                                        
                                <td><h5>{{ borrow.borrow_date.date  }}</h5></td>
                                <td><h5>{{  borrow.copy.owner.username }}</h5></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <div style="text-align: center;">
                                <div class="pagination">
                                  <span class="step-links">
                                    {% if borrowed_copies.has_previous %}
                                      <a href="?page=1" style="font-weight: bold; font-size: 16px">&laquo; first</a>
                                      <a href="?page={{ borrowed_copies.previous_page_number }}" style="font-weight: bold; font-size: 16px">previous</a>
                                    {% endif %}
                                
                                    <span class="current-page" style="font-weight: bold; font-size: 16px">
                                      Page {{ borrowed_copies.number }} of {{ borrowed_copies.paginator.num_pages }}.
                                    </span>
                                
                                    {% if borrowed_copies.has_next %}
                                      <a href="?page={{ borrowed_copies.next_page_number }}" style="font-weight: bold; font-size: 16px">next</a>
                                      <a href="?page={{ borrowed_copies.paginator.num_pages }}" style="font-weight: bold; font-size: 16px">last &raquo;</a>
                                    {% endif %}
                                  </span>
                                </div>
                              </div> 
                        </div>
                    </div>

                
            </div>
            <!-- /col end-->
        </div>
        <!-- /row end-->
    </div>
    </div>
        <!-- Delete Modal HTML -->
        

</main>
{% endblock %}

templates/pages/demo.html
{% extends 'pages/base.html' %}
{% load static %}
{% block basetemplate %}
<main>
    <center>
        <h2>Hello, This is Demo Page</h2>
    </center>

</main>
{% endblock %}

templates/pages/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}


<main>

 

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">All Books</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
              
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/pages/owned_copy.html
{% extends 'pages/base.html' %}
{% load static %}
{% block basetemplate %}

<main>
    <div class="event-schedule-area-two bg-color pad100">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-20">
                <div class="section-title text-center">
                    <div class="title-text">
                        <h2>Owned Copy</h2>
                        
                    </div>
                </div>
            </div>
            <!-- /.col end-->
        </div>
        <!-- row end-->
        <div class="row">
            <div class="col-xl-20">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade active show" id="home" role="tabpanel">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
<!--                                        <th class="text-center" scope="col">Date</th>-->  
                                        <th scope="col">Sl</th>
                                        <th scope="col">Title</th>
                                        <th scope="col">Copy No</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Borrowed date</th>
                                        <th scope="col">Borrowed by</th>
                                    </tr>
                                </thead>
                                <tbody>
                                 {% for copy in owned_copies %}
                                    <tr class="inner-box">
                                        <td>
                                           </h2>{{ forloop.counter }}</h2>
                                        </td>
                                        <td>
                                            <div class="event-wrap">
                                                <h5 style="color: green">{{copy.book.title}}</a></h5>
                                            </div>
                                        </td>
                                        <td>
                                            
                                                <h5>{{ copy.copy}}</h5>
                                            
                                        </td>
                                        
                                        {% if copy.status == 'borrowed' %}
                                        <td>
                                            <h5 style="color: red">{{copy.status}}</h5>
                                        </td>
                                <td><h5>{{ copy.borrow.first.borrow_date.date  }}</h5></td>
                                <td><h5>{{ copy.borrow.first.borrower.username }}</h5></td>
                                
                                       {% else %}
                                       <td>
                                        <h5 style="color: black">{{copy.status}}</h5>
                                      </td>
                                       <td><h3>-</h3></td>
                                       <td><h3>-</h3></td> 
                                        
                                       {% endif %} 
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                            <div style="text-align: center;">
                                <div class="pagination">
                                  <span class="step-links">
                                    {% if owned_copies.has_previous %}
                                      <a href="?page=1" style="font-weight: bold; font-size: 16px">&laquo; first</a>
                                      <a href="?page={{ owned_copies.previous_page_number }}" style="font-weight: bold; font-size: 16px">previous</a>
                                    {% endif %}
                                
                                    <span class="current-page" style="font-weight: bold; font-size: 16px">
                                      Page {{ owned_copies.number }} of {{ owned_copies.paginator.num_pages }}.
                                    </span>
                                
                                    {% if owned_copies.has_next %}
                                      <a href="?page={{ owned_copies.next_page_number }}" style="font-weight: bold; font-size: 16px">next</a>
                                      <a href="?page={{ owned_copies.paginator.num_pages }}" style="font-weight: bold; font-size: 16px">last &raquo;</a>
                                    {% endif %}
                                  </span>
                                </div>
                              </div> 
                        </div>
                    </div>

                
            </div>
            <!-- /col end-->
        </div>
        <!-- /row end-->
    </div>
    </div>
        <!-- Delete Modal HTML -->
        

</main>
{% endblock %}

templates/pages/view_book_list.html
{% extends 'pages/base.html' %}
{% load static %}
{% block basetemplate %}

<main>
    <div class="event-schedule-area-two bg-color pad100">
        <style>
             .tab-content {
                background-color: #28B463;
                color: #fff;
                font-size: 17px;
                font-family: Times New Roman;
            }
        </style>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-20">
                <div class="section-title text-center">
                    <div class="title-text">
                        <h2>Book List</h2>

                    </div>
                </div>
            </div>
            <!-- /.col end-->
        </div>
        <!-- row end-->
        <div class="row">
            <div class="col-xl-20">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade active show" id="home" role="tabpanel">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
<!--                                        <th class="text-center" scope="col">Date</th>-->
                                        <th scope="col">Sl</th>
                                        <th scope="col">Cover</th>
                                        <th scope="col">Title</th>
                                        <th scope="col">Author</th>
                                        <th scope="col">Publisher</th>
                                        {% comment %} <th scope="col">Category</th> {% endcomment %}
                                        <th scope="col">Edition</th>
                                        <th scope="col">In Stock</th>
                                        <th class="text-center" scope="col">Action</th>
<!--                                        <th class="text-center" scope="col">Venue</th>-->
                                    </tr>
                                </thead>
                                <tbody>
                                 {% for product in products %}
                                    <tr class="inner-box">
                                        <td>
                                           </h2>{{ forloop.counter }}</h2>
                                        </td>
                                        <td>
                                            <div class="event-img">
                                                <img src="{{ product.image.url}}" alt="" />

                                            </div>
                                        </td>
                                        <td>
                                            <div class="event-wrap">
                                                <h3><a href="{{ product.get_absolute_url }}">{{ product.title}}</a></h3>
                                            </div>
                                        </td>
                                        <td>
                                            <h5>{{ product.author}}</h5>
                                        </td>
                                        <td>
                                            <h5>{{  product.publisher  }}</h5>
                                        </td>

                                        <td>
                                            <h5>{{ product.edition }}</h5>
                                        </td>
                                        <td>
                                            <input type="checkbox" {% if product.in_stock %}checked{% endif %} disabled>
                                        </td>

                                        <td class="h5 mb-4 text-gray-800">
<!--                                            <a href="#editEmployeeModal-{{ forloop.counter }}" class="edit btn btn-primary btn-sm" data-toggle="modal" >Edit</a>-->
                                            <a href="#deleteModal-{{ forloop.counter }}" class="edit btn btn-danger btn-sm" data-toggle="modal" >Delete</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                        </div>
                        <div style="text-align: center;">
                            <div class="pagination">
                              <span class="step-links">
                                {% if products.has_previous %}
                                  <a href="?page=1" style="font-weight: bold; font-size: 16px">&laquo; first</a>
                                  <a href="?page={{ products.previous_page_number }}" style="font-weight: bold; font-size: 16px">previous</a>
                                {% endif %}

                                <span class="current-page" style="font-weight: bold; font-size: 16px">
                                  Page {{ products.number }} of {{ products.paginator.num_pages }}.
                                </span>

                                {% if products.has_next %}
                                  <a href="?page={{ products.next_page_number }}" style="font-weight: bold; font-size: 16px">next</a>
                                  <a href="?page={{ products.paginator.num_pages }}" style="font-weight: bold; font-size: 16px">last &raquo;</a>
                                {% endif %}
                              </span>
                            </div>
                          </div>
                        </div>
                    </div>


            </div>
            <!-- /col end-->
        </div>
        <!-- /row end-->
    </div>
    </div>

        <!-- Delete Modal HTML -->
        {%for product in products %}
            <div id="deleteModal-{{forloop.counter}}" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <form>
                            <div class="modal-header">
                                <h4 class="modal-title">Delete Book</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            </div>
                            <div class="modal-body">
                                <p>Are you sure, you want to delete <strong style="color:red;">{{getdata.1}}</strong>  Records?</p>
                                <p class="text-danger"><medium>This action cannot be undone.</medium></p>


                            </div>
                            <div class="modal-footer">
                                <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                                <a href="#" class="edit btn btn-danger btn-sm"  value="Delete"  >Delete</a>
                            </div>
                        </form>


                    </div>
                </div>
            </div>


        {% endfor %}



</main>




{% endblock %}