core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('home.urls')),
    path('', include('library.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path

from . import views

app_name = 'library'

urlpatterns = [
    path('view_all_book/', views.all_books, name='all_books'),
    path('add/book/',views.add_book,name='add_book'),
    path('add/category/',views.add_category,name='add_category'),
    path('book_added/', views.book_added, name='book_added'),
    path('item/<slug:slug>/', views.book_detail, name='book_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('add/copy/', views.add_copy_form, name='add_copy'),
    path('owned/copy/', views.owned_copy, name='owned_books'),
    path('borrowed/copy/', views.borrowed_copy, name='borrowed_books'),
    path('borrow/<slug:slug>/', views.borrow_copy, name='borrow_copy'),
    path('searchbooks/', views.search_books, name='search_books'),

]

templates/pages/books/category.html
{% extends "pages/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Books{% endif %}
{% endblock %}
{% block basetemplate %}


<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
              
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/pages/books/detail.html
{% extends "pages/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{{msg}}
{% endblock %}
{% block basetemplate %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
                <div class="row p-3">
                    <div class="col">
                        <form method="post" action="{% url 'library:book_detail' product.slug %}">
                            {% csrf_token %}
                            <h2>Write a Review</h2>
                            <div class="mb-3">
                                <label for="reviewText" class="form-label">Review Text</label>
                                <textarea class="form-control" name="content" rows="3"></textarea>
                            </div>
                            <div class="mb-3">
                                <label for="rating" class="form-label">Rating:</label>
                                <select class="form-select" aria-label="Rating" name="rating">
                                    <option selected disabled>Select rating</option>
                                    <option value="1">1 star</option>
                                    <option value="2">2 stars</option>
                                    <option value="3">3 stars</option>
                                    <option value="4">4 stars</option>
                                    <option value="5">5 stars</option>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit Review</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4" style="font-size: 24px; color: blue;">{{ product.title }}</h1>
                {% comment %} <p><span class="lead">Author:</span> {{ product.author }}</p>
                <p><span class="lead">Published By:</span> {{ product.publisher }}</p>
                <p><span class="lead">Edition:</span>{{ product.edition }} </p> {% endcomment %}
                <p><strong><span class="lead">Total Copies:</span></strong> <span style="font-size: 24px; font-weight: bold; color: green">{{ product.copies.count }}</span></p>
                <p><strong><span class="lead">Description:</span></strong> <span style="color:black;font-weight:bold;">{{ product.description }}</span></p>
                <div class="border">
                    <div class="row p-3">

                            <div class="col-6">
                                <a id="button" href="{% url 'library:borrow_copy' product.slug  %}" class="btn btn-secondary btn-sm" data-url="{% url 'library:borrow_copy' product.slug  %}">Borrow Book</a>
                                {% if msg %}
                             <p>{{ msg }}</p>
                               {% endif %}
                                
                            </div>                                
                        </div>                              
                    </div>                   
                </div>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                            <big><strong>{{ message }}</strong></big>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}


                <div class="row p-3">
                    <div class="row p-3">
                    <div class="col">
                        <h2>Reviews & Rating</h2>
                        {% if product.reviews.all %}
                            {% for review in page_obj %}
                              <div class="rating">
                                {% if review.rating == 1 %}
                                <span class="fa fa-star" style="color: gold;"></span>
                                <span class="fa fa-star star-white"></span>
                                <span class="fa fa-star star-white"></span>
                                <span class="fa fa-star star-white"></span>
                                <span class="fa fa-star star-white"></span>


                            {% elif review.rating == 2 %}

                            <span class="fa fa-star" style="color: gold;"></span>
                            <span class="fa fa-star" style="color: gold;"></span>
                            <span class="fa fa-star star-white"></span>
                            <span class="fa fa-star star-white"></span>
                            <span class="fa fa-star star-white"></span>

                            {% elif review.rating == 3 %}
                            <span class="fa fa-star" style="color: gold;"></span>
                            <span class="fa fa-star" style="color: gold;"></span>
                            <span class="fa fa-star" style="color: gold;"></span>
                            <span class="fa fa-star star-white"></span>
                            <span class="fa fa-star star-white"></span>

                            {% elif review.rating == 4 %}
                            <span class="fa fa-star" style="color: gold;"></span>
                            <span class="fa fa-star" style="color: gold;"></span>
                            <span class="fa fa-star" style="color: gold;"></span>
                            <span class="fa fa-star" style="color: gold;"></span>
                            <span class="fa fa-star star-white"></span>
                            {% else %}
                            <span class="fa fa-star" style="color: gold;"></span>
                            <span class="fa fa-star" style="color: gold;"></span>
                            <span class="fa fa-star" style="color: gold;"></span>
                            <span class="fa fa-star" style="color: gold;"></span>
                            <span class="fa fa-star" style="color: gold;"></span>
                            {% endif %}

                            </div>
                                <div class="card mb-3">
                                    <div class="card-body">
                                        <p class="card-text">{{ review.content }}</p>
                                        <p class="card-text"><small class="text-muted">by {{ review.user.username }}</small></p>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <p>No reviews yet.</p>
                        {% endif %}
                    </div>
                </div> 
                <div style="text-align: center;">
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page=1">&laquo; first</a>
                                <a href="?page={{ page_obj.previous_page_number }}">&lsaquo; previous</a>
                            {% endif %}

                            <span class="current-page">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">next &rsaquo;</a>
                                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>

                  </div>

                
            </div>
        </div>
    </main>

</div>
{% endblock %}

templates/pages/books/searchbooks.html
{% extends 'pages/base.html' %}
{% load static %}
{% block basetemplate %}
    <h1 align="center">Search Option</h1>
    <form method="GET" align="center">
        {%csrf_token%}

        {{filters.form}}
    <input type="submit" value='Search' name="">
    </form>
<main>
    <div class="event-schedule-area-two bg-color pad100">
        <div class="container-fluid">
        <div class="row">
        <div class="col-xl-20">
        <div class="section-title text-center">
        <div class="title-text">
{% comment %}
            <h2>Book List</h2>
{% endcomment %}       
        </div>
        </div>
        </div>
        <!-- /.col end-->
        </div>
        <!-- row end-->
        <div class="row">
        <div class="col-xl-20">
        <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade active show" id="home" role="tabpanel">
        <div class="table-responsive">
        <table class="table">
        <thead>
            <tr>
            <!-- <th class="text-center" scope="col">Date</th>-->
                <th scope="col">Sl</th>
                <th scope="col">Book Name</th>
                <th scope="col">Author Name</th>
                <th scope="col">Catagory</th>

                <th class="text-center" scope="col">Action</th>
            <!-- <th class="text-center" scope="col">Venue</th>-->
            </tr>
        </thead>
        <tbody>
        {% for i in Books %}
            <tr class="inner-box">
                    <td>
                        <h5>{{ forloop.counter }}</h5>
                    </td>
                    <td>
                    <div class="event-wrap">
                         <h3><a href="#">{{ i.title }}</a></h3>
                    </div>
                    </td>
                    <td>
                        <h6><a href="#">{{ i.author }}</a></h6>
                    </td>
                    <td>
                        <h6><a href="#">{{ i.category }}</a></h6>
                    </td>
                    <td class="h5 mb-4 text-gray-800">
                    <!-- <a href="#editEmployeeModal-{{ forloop.counter }}" class="edit btn btn-primary btn-sm" data-toggle="modal" >Edit</a>-->
                    <a href="#deleteModal-{{ forloop.counter }}" class="edit btn btn-danger btn-sm" data-toggle="modal" >Delete</a>
                    </td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
        </div>
        </div>
        </div>
        <!-- /col end-->
        </div>
        <!-- /row end-->
        </div>
        </div>
</main>


{%endblock%}